### ISSUE TITLE
ZeroDivisionError: float division

### ISSUE THREAD

**Issue by silvewheat** [Rosemeis/flashpcangsd#2]
Hello,

When I run:
python emu.py -plink /data/chrAuto -e 2 -threads 24 -out out/chrAuto
An error occurred:
![image](https://user-images.githubusercontent.com/19344997/112242147-38b7ad80-8c86-11eb-88e9-73e3041a3877.png)
What should I do?

Best,
Yudong Cai

**Comment by Rosemeis** [comment]
Hi Yudong,

It seems like that there aren't any minor alleles in some sites. You should perform MAF filtering in PLINK before using EMU.

Best,
Jonas

**Comment by silvewheat** [comment]
Hi Jonas,

The problem solved after MAF filtering. Thank you!

Best,
Yudong
