### ISSUE TITLE
ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by jordanbemmels** [Rosemeis/flashpcangsd#3]
Hi Jonas,

I'm trying out EMU and the program begins running fine, but then throws an error. My command is:

`python /home/0_PROGRAMS/emu/emu.py -plink maf0139_54ind_unrelated_10kbp_noZ_v1 -e 2 -threads 4 -out maf0139_54ind_unrelated_10kbp_noZ_v1.emu`

and the terminal output is:

````
EMU 0.71

Reading in data matrix from PLINK files.
Loaded 67 samples and 11400 sites.
Estimating population allele frequencies.

Performing EMU using 2 eigenvector(s).
Using accelerated EM scheme (SqS3)
Initiating accelerated EM scheme (1)
Individual allele frequencies estimated (2). RMSE=0.013247709172857036
Individual allele frequencies estimated (3). RMSE=0.00011796467001020907
Individual allele frequencies estimated (4). RMSE=5.670894510581786e-06
Individual allele frequencies estimated (5). RMSE=1.566263133332578e-07
Estimation of individual allele frequencies has converged.
Inferring set of eigenvector(s).
Traceback (most recent call last):
  File "/home/0_PROGRAMS/emu/emu.py", line 167, in <module>
    args.cost_step, args.threads)
  File "/home/0_PROGRAMS/emu/shared.py", line 174, in emuAlgorithm
    U, s, V = randomized_svd(E, K, n_iter=svd_power)
  File "/home/0_PROGRAMS/jordan_conda/conda/envs/jordan-emu-python3_7_6/lib/python3.7/site-packages/sklearn/utils/extmath.py", line 348, in randomized_svd
    power_iteration_normalizer, random_state)
  File "/home/0_PROGRAMS/jordan_conda/conda/envs/jordan-emu-python3_7_6/lib/python3.7/site-packages/sklearn/utils/extmath.py", line 232, in randomized_range_finder
    Q, _ = linalg.lu(safe_sparse_dot(A, Q), permute_l=True)
  File "/hhome/jordan/.local/lib/python3.7/site-packages/scipy/linalg/decomp_lu.py", line 210, in lu
    a1 = asarray_chkfinite(a)
  File "/hhome/jordan/.local/lib/python3.7/site-packages/numpy/lib/function_base.py", line 499, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs
````

Googling a bit, I found that this might be an error in trying to do PCA in scikit-learn, but I'm not sure. I found one user got a similar error in scikit-learn (not related to EMU), but the error was resolved with the following environment:

python=3.7.6
numpy=1.18.1
scipy=1.4.1
cython=0.29.15
scikit-learn=0.22.1

So, I tried replicating that environment with conda, but it did not fix the error with EMU.

Any idea what's going on? Is there a particular version of python and its dependencies that must be installed to run EMU?

Thanks very much,
Jordan

**Comment by Rosemeis** [comment]
Hi Jordan,

Thanks for trying out EMU!

It could potentially be a minor allele frequency problem. Can you try and re-run the command with the following argument added, "-maf 0.05".

Best,
Jonas

**Comment by jordanbemmels** [comment]
Hi Jonas,

Thanks for the speedy reply! You were right: adding the -maf flag fixed this.

I had thought that my data were filtered to maf = 0.0139 already, but apparently this was not the case. I added the flag "-maf 0.0139" when running EMU, and EMU retained only 10,333 out of my 11,400 sites. Most likely something unexpected happened in my upstream filtering using ANGSD to create the input files.

Anyway, thank you! Sorry it was was silly problem. Should be ok to close the issue now.

Best,
Jordan

**Comment by Rosemeis** [comment]
Cheers, happy to hear.

Best,
Jonas
