### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by archgen** [Rosemeis/flashpcangsd#5]
Hi @Rosemeis, I am trying to install emu following the tutorial. I've come up to the below error and wondering if you have had any luck installing on a mac. I'm using Ventura 13.0.1.
Many thanks,
Matthew 

(emu) matthias@Matthews-MacBook-Pro-2 emu % python setup.py build_ext --inplace
running build_ext
building 'emu.shared_cy' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/matthias/opt/anaconda3/envs/emu/include -fPIC -O2 -isystem /Users/matthias/opt/anaconda3/envs/emu/include -I/Users/matthias/opt/anaconda3/envs/emu/lib/python3.10/site-packages/numpy/core/include -I/Users/matthias/opt/anaconda3/envs/emu/lib/python3.10/site-packages/numpy/core/include -I/Users/matthias/opt/anaconda3/envs/emu/include/python3.10 -c emu/shared_cy.c -o build/temp.macosx-10.9-x86_64-cpython-310/emu/shared_cy.o -fopenmp -g0
clang: error: unsupported option '-fopenmp'
error: command '/usr/bin/clang' failed with exit code 1

**Comment by Rosemeis** [comment]
Sorry for the late reply. The issue is that the standard gcc compiler with macOS does not include OpenMP. You therefore need to install the gcc with homebrew.

Best,
Jonas
