### ISSUE TITLE
Error running emu

### ISSUE THREAD

**Issue by mguevarasouza** [Rosemeis/flashpcangsd#6]
@Rosemeis  I followed the guide to install emu. When i tried to run  this example  

python emu.py -plink data/humanOrigins_7worldPops -e 4 -t 4 -o plink_emu

i get

ImportError: cannot import name 'shared' from 'emu'

Any ideas?

Thank you

**Comment by Rosemeis** [comment]
Hi,

After install you need to run it as:
`emu --plink data/humanOrigins_7worldPops -e 4 -t 4 -o plink_emu`
Hope that solves the issue.

Best,
Jonas

**Comment by mguevarasouza** [comment]
Than fixed the issue!! Thanks a lot for the fast response!!
